biojs/biojs-frontend

.travis.yml
Travis has been set up. Unit and e2e tests are yet to be written.
=> setup travis

src/components/About.vue, src/router/index.js
=> Created the "About" page

package-lock.json, package.json, src/components/SearchComponent.vue
Implemented a "fuzzy search" through Vue for the components. A fuzzy search basically searches by breaking the query and not for the exact same query and assigns scores to the results, though, of course it gives maximum score to the result which matches exactly the query. I think that fuzzy search is important for a platform like BioJS since there are a lot of jargons and technical terms used so it will be really helpful for a user with not the best knowledge of bioinformatics.
Screenshots:
=> Fuzzy search

src/components/ComponentTable.vue, src/components/Components.vue, src/components/Home.vue, src/components/SearchComponent.vue
You can now click on a component and view its details.
Experience it here: http://139.59.93.32/biojs-frontend/dist/#/components
=> Added links to specific component everywhere

src/components/About.vue, src/components/Component.vue, src/components/ComponentStat.vue, src/components/Components.vue, src/components/Contributor.vue, src/components/Guide.vue, src/components/SearchComponent.vue
=> Documentation

package-lock.json, package.json, src/components/Component.vue, src/components/ComponentStat.vue, src/components/ComponentTable.vue, src/components/Components.vue, src/components/Contributor.vue, src/components/SearchComponent.vue, src/components/Visualization.vue, src/router/index.js
Elaborate documentation for the search component will be added.
=> Updated documentation

.travis.yml, package-lock.json, package.json, src/components/Component.vue, src/components/ComponentTable.vue, src/components/NavBar.vue, src/router/index.js, test/unit/karma.conf.js, test/unit/specs/ComponentTable.spec.js
=> Component table

src/components/Component.vue
=> Added biojs.io URL in components' page

src/components/RandomSnippets.vue, src/router/index.js
Once merged, the URL for viewing visualizations will be: http://139.59.93.32/biojs-frontend/dist/#/random/6
Snapshot:
=> URL for random visualizations

src/components/Components.vue, src/components/SearchComponent.vue, src/components/SearchPage.vue, src/router/index.js
@rowlandm, I've created a functionality for which we have discussed. The basic functionality is ready and I will be improving upon the UI.
The search page doesn't show the description, author, etc. as it will require an API call for each component in the results which will slow down the process. Hope this is fine.
=> Search tag upon clicking a tag

src/components/Component.vue, src/components/ComponentStat.vue, src/components/SearchComponent.vue, src/components/Visualization.vue
As discussed in the weekly call, I've directed the visualizations to the workmen as a placeholder.
=> Visualization placeholder

src/components/Components.vue
=> Generate list of random components from the components page

src/components/ContactUs.vue, src/router/index.js
=> Contact Us page

src/components/Component.vue, src/components/Components.vue, src/components/Contributor.vue
1. biojs.io URL should show error if workmen response is 404
2. Added npm URL to component's page
3. Make the tags clickable in component's page
4. Open contributor profile upon clicking contributor
=> Component page

src/components/Component.vue
Fix issue https://github.com/biojs/biojs-frontend/issues/33
=> Fix npm URL

index.html, src/components/Component.vue, src/components/ComponentTable.vue, src/components/Components.vue, src/components/Loader.vue
When data is loading:
When data loads:
=> Show loader while data loads

.travis.yml, src/components/About.vue
Remove the height property of #about in About.vue
Fixes #66
=> Fix overlap in about section

src/components/Components.vue, src/components/NavBar.vue
* set max-width:30% so as to fit side components
* Set cursor at hamburger as pointer
=> Resolved issue #85

src/components/About.vue, src/components/Components.vue, src/components/ContactUs.vue, src/components/Guide.vue, src/components/NavBar.vue
To highlight on a small screen, I set a background color but text of nav links were not properly aligned in the box, therefore I had to do some UI changes to side nav on mobile. (As shown in photo)
**Before/After**
=> Highlight selected nav item (#62)

src/components/NavBar.vue
=> Added link to go to homepage for mobile.

src/components/NavBar.vue
The navbar earlier used conditional statements to add class to the currently active route. Use the active-class prop of `router-links` component.
fixes #95
=> use active-class props in router-link to add class to the active route

src/components/About.vue, src/components/Component.vue, src/components/Components.vue, src/components/ContactUs.vue, src/components/Footer.vue, src/components/Guide.vue, src/components/Home.vue
=> Added footer on all pages

README.md, src/components/NavBar.vue
All the information on guide page is now shifted to README.md and guide page points to https://edu.biojs.net.
Fixes #34
=> Guide page points to biojs EDU website and updated README.md

src/components/Component.vue, src/components/NavBar.vue
Shows readme.md of the component's repository from github on the component page.
fixes #56
=> Show Readme file from github in Component.vue page

src/components/Component.vue, src/components/ComponentStat.vue
Changes have been made to remove eslint errors that were introduced by #90, as pointed out in [this](https://github.com/biojs/biojs-frontend/pull/90#pullrequestreview-226368065) discussion.
=> style: fix indentation and spacing
